# grants access to cmdhub from within the cluster

apiVersion: v1
kind: Service
metadata:
  name: cmdhub-np
spec:
  type: NodePort
  selector:
    app: cmd-hub
  ports:
    - protocol: TCP
      port: 80 # incoming port
      targetPort: 8000 # requests sent to port 80 will go to port 8000


